spring:
  data:
    redis:
      host: 192.168.88.130
      port: 6379
      password: 123456
      database: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/code_fix?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456

mq:
  rocketmq:
    name-server: 192.168.88.130:9876

agent:
  embedding:
    base-url: http://localhost:11434

py:
  url: http://localhost:8000/analyze