server:
  port: 8080

spring:
  profiles:
    active: dev          # 默认激活 dev

mq:
  rocketmq:
    consumer:
      groupName: cid_status_group_test
      topics: agent_status_topic
    heartbeat-consumer:
      groupName: cid_heartbeat_group
      topics: agent_heartbeat_topic
    producer:
      groupName: cid_task_group
      topics: agent_task_topic
    topic:
      status: agent_status_topic
      statusQueueNum: 8
      heartbeat: agent_heartbeat_topic
      heartbeatQueueNum: 8

agent:
  embedding:
    provider: ollama
    model: nomic-embed-text:latest
    dimension: 768
  memory:
    vector:
      distance-metric: COSINE
      index-name: 'agent_task_memory_idx'
      key-prefix: 'agent:task-memory:'