server:
  port: 8080

spring:
  data:
    redis:
      port: ...
      host: ...
      password: ...
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://[ip]:[port]/code_fix?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: ...
    password: ...


mq:
  rocketmq:
    name-server: [ip]:[port]
    consumer:
      groupName: cid_status_group_test
      topics: agent_status_topic
    heartbeat-consumer:
      groupName: cid_heartbeat_group
      topics: agent_heartbeat_topic
    producer:
      groupName: cid_task_group
      topics: agent_task_topic
    topic:
      status: agent_status_topic
      statusQueueNum: 8
      heartbeat: agent_heartbeat_topic
      heartbeatQueueNum: 8

py:
  url: #py端api地址