server:
  port: 8080

spring:
  profiles:
    active: dev          # 默认激活 dev

mq:
  rocketmq:
    consumer:
      groupName: cid_status_group_test
      topics: agent_status_topic
    heartbeat-consumer:
      groupName: cid_heartbeat_group
      topics: agent_heartbeat_topic
    producer:
      groupName: cid_task_group
      topics: agent_task_topic
    topic:
      status: agent_status_topic
      statusQueueNum: 8
      heartbeat: agent_heartbeat_topic
      heartbeatQueueNum: 8

agent:
  embedding:
    provider: ollama
    model: nomic-embed-text:latest
    dimension: 768
  memory:
    vector:
      distance-metric: COSINE
      index-name: 'agent_task_memory_idx'
      key-prefix: 'agent:task-memory:'

#!!!! dev !!!!! 配置模板
#spring:
#  data:
#    redis:
#      host: xxxx
#      port: xxxx
#      password: xxxx
#      database: 0
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://xxxx:xxx/code_fix?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
#    username: xxx
#    password: xxx
#
#mq:
#  rocketmq:
#    name-server: xxx:xxx
#
#agent:
#  embedding:
#    base-url: http://xxxx:xxxx